version: '3.7'

services:
  gateway:
    image: agate/gateway:latest
    # build: ./
    container_name: agate-gateway
    # restart: always
    ports:
      - 5454:5454
      - 4004:4004
    volumes:
      - ./gateway/logs:/agate/gateway/logs
      - ./gateway/config.json:/agate/gateway/config.json
    depends_on:
      - consul
  
  manager:
    image: agate/manager
    # build: ./
    container_name: agate-manager
    # restart: always
    ports:
      - 8080:8080
    volumes:
      - ./manager/logs:/agate/manager/logs
      - ./manager/data:/agate/manager/data
      - ./manager/application.properties:/agate/manager/application.properties
    depends_on:
      - consul
  
  consul:
    image: consul
    container_name: agate-consul
    # restart: always
    ports:
      - 8500:8500
    volumes:
      - ./consul:/consul/data