version: '3.7'

services:
  consul:
    image: consul:1.7
    container_name: agate-consul
    # restart: always
    ports:
      - 8500:8500
    volumes:
      - ./consul:/consul/data

  admin:
    image: agate/admin:1.2.0
    # build: ./
    container_name: agate-admin
    # restart: always
    ports:
      - 8888:8888
    environment:
      ACTIVE_PROFILE: "install"
    volumes:
      - ./admin/logs:/agate-admin/logs
      - ./admin/data:/agate-admin/data
      - ./admin/config:/agate-admin/config
    depends_on:
      - consul

  gateway:
    image: agate/gateway:1.2.0
    # build: ./
    container_name: agate-gateway
    # restart: always
    ports:
      - 4444:4444
      - 4004:4004
    volumes:
      - ./gateway/logs:/agate-gateway/logs
      - ./gateway/config:/agate-gateway/config
    depends_on:
      - consul
